# Site settings
title: DGPR
url: "https://dragonappear.github.io"
baseurl: ""
description: >
    dragonappear

# My information
email: dragonappear1@gmail.com
author: dragonappear
profile: dgpr
github_username: dragonappear
gitbook_username: dragonappear
linkedin_username: dgpr
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
# giscus:
#   repo: dragonappear/dragonappear.github.io
#   repo_id: SAMPLE-VALUE
#   category: Announcements
#   category_id: SAMPLE-VALUE

# google_analytics:
#   ua: SAMPLE-VALUE
#   encrypted_ua: THIS-IS-SAMPLE-VALUE

# google_adsense:
#   client: SAMPLE-VALUE

blame: "https://github.com/dragonappear/dragonappear.github.io/blame/master/_wiki"
edit: "https://github.com/dragonappear/dragonappear.github.io/edit/master/_wiki"
issue: "https://github.com/dragonappear/dragonappear.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
